import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import './App.css'

type Source = { id: string; type: string; title: string; detail: string; content?: string }
type Claim = { text: string; evidence: string[]; certainty: 'supported' | 'inferred' | 'unknown' }
type Brief = { coverage: Record<string, boolean>; warnings: string[]; sections: { title: string; claims: Claim[] }[] }
type Project = { id: string; name: string; repositoryPath: string }

const demoBrief: Brief = { coverage: { git: true, notes: true, workingTree: true }, warnings: ['This is a local preview. Add a repository to generate a brief from your own evidence.'], sections: [
  { title: 'Goal', claims: [{ text: 'Make large report exports reliable without depending on the remote rendering service.', evidence: ['note:decision-export'], certainty: 'supported' }] },
  { title: 'Where you left off', claims: [{ text: 'The local export path was implemented; test changes remain uncommitted.', evidence: ['git:working-tree', 'commit:3ad9e1f'], certainty: 'supported' }] },
  { title: 'What changed', claims: [{ text: 'Export generation moved from a remote service to a local implementation.', evidence: ['commit:3ad9e1f', 'note:decision-export'], certainty: 'supported' }] },
  { title: 'Decisions and reasoning', claims: [{ text: 'Local generation was chosen to remove dependency on intermittent service latency.', evidence: ['note:decision-export'], certainty: 'supported' }] },
  { title: 'Open work and blockers', claims: [{ text: 'Large exports may still fail; no passing result is recorded.', evidence: ['checkpoint:last'], certainty: 'supported' }] },
  { title: 'Next action', claims: [{ text: 'Reproduce the large-export failure with the existing test changes, then record the result.', evidence: ['checkpoint:last', 'git:working-tree'], certainty: 'inferred' }] },
] }
const demoSources: Source[] = [
  { id: 'note:decision-export', type: 'NOTE', title: 'notes/export-decision.md', detail: 'Switched to local generation to avoid remote service latency.' }, { id: 'commit:3ad9e1f', type: 'COMMIT', title: '3ad9e1f — Implement local export generator', detail: '10 days ago' }, { id: 'git:working-tree', type: 'WORKTREE', title: 'Uncommitted test changes', detail: 'tests/export-large.test.ts' }, { id: 'checkpoint:last', type: 'CHECKPOINT', title: 'Last checkpoint', detail: 'Large exports still fail.' },
]

function App() {
  const [projects, setProjects] = useState<Project[]>([]); const [active, setActive] = useState<Project | null>(null); const [brief, setBrief] = useState<Brief>(demoBrief); const [evidence, setEvidence] = useState<Source | null>(null); const [showAdd, setShowAdd] = useState(false); const [checkpointOpen, setCheckpointOpen] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  useEffect(() => { fetch('/api/projects').then(response => response.ok ? response.json() : []).then(setProjects).catch(() => {}) }, [])
  async function resume(project: Project) { setActive(project); setBusy(true); setError(''); try { const response = await fetch(`/api/projects/${project.id}/brief`, { method: 'POST' }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setBrief(data.brief); setSources(data.sources) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not generate a brief.') } finally { setBusy(false) } }
  const [sources, setSources] = useState<Source[]>(demoSources)
  async function addProject(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); const fields = new FormData(event.currentTarget); try { const response = await fetch('/api/projects', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ repositoryPath: fields.get('repositoryPath'), notesPath: fields.get('notesPath'), excludedPaths: String(fields.get('excludedPaths') || '').split(',').map(value => value.trim()).filter(Boolean) }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setProjects(items => [data.project, ...items]); setShowAdd(false); await resume(data.project) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not add project.') } finally { setBusy(false) } }
  function exportMarkdown() { const markdown = `# ${active?.name || 'Project'} — Re-entry brief\n\n${brief.sections.map(section => `## ${section.title}\n\n${section.claims.map(claim => `- ${claim.text}`).join('\n')}`).join('\n\n')}\n`; const url = URL.createObjectURL(new Blob([markdown], { type: 'text/markdown' })); const link = document.createElement('a'); link.href = url; link.download = 're-entry-brief.md'; link.click(); URL.revokeObjectURL(url) }
  async function saveCheckpoint() { if (!active) return; const element = document.querySelector<HTMLTextAreaElement>('.checkpoint textarea'); const content = element?.value.trim(); if (!content) return; const response = await fetch(`/api/projects/${active.id}/checkpoints`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ content }) }); if (response.ok) { setCheckpointOpen(false); await resume(active) } }
  return <main>
    <aside><div className="brand"><span className="brand-mark">↗</span><span>re-entry</span></div><button className="new-project" onClick={() => setShowAdd(true)}>+ Add project</button><p className="sidebar-label">YOUR PROJECTS</p><nav>{projects.length ? projects.map(project => <button key={project.id} className={active?.id === project.id ? 'project selected' : 'project'} onClick={() => resume(project)}><span className="repo-dot" />{project.name}</button>) : <p className="empty">No projects yet</p>}</nav><div className="privacy"><span>◉</span><p><strong>Local by default</strong><br />Sources stay on this computer. You choose any provider before excerpts leave it.</p></div></aside>
    <section className="workspace"><header><div className="crumb"><span>{active?.name || 'Export reliability'}</span><em> / Re-entry brief</em></div><div className="header-actions"><button onClick={exportMarkdown}>Export Markdown</button><button className="primary" onClick={() => setCheckpointOpen(true)}>Leave checkpoint</button></div></header><div className="brief-wrap"><div className="brief-heading"><div><p className="eyebrow">RE-ENTRY BRIEF</p><h1>{active?.name || 'Export reliability'}</h1><p className="subhead">{active ? `Generated from ${active.repositoryPath}` : 'A sample brief — add your repository to begin'}</p></div><div className="generated">{busy ? 'Reading sources…' : 'Updated just now'}<span className="live-dot" /></div></div>{error && <div className="notice">⚠ {error}</div>}{brief.warnings.map(warning => <div key={warning} className="notice">⚠ {warning}</div>)}<div className="coverage"><span>Source coverage</span>{Object.entries(brief.coverage).map(([key, value]) => <span key={key} className={value ? 'covered' : 'missing'}>{value ? '●' : '○'} {key === 'workingTree' ? 'working tree' : key}</span>)}</div><div className="sections">{brief.sections.map((section, index) => <article className="brief-section" key={section.title}><div className="section-number">0{index + 1}</div><div><h2>{section.title}</h2>{section.claims.map((claim, claimIndex) => <div className="claim" key={claimIndex}><p>{claim.text}</p><div className="claim-foot"><span className={`certainty ${claim.certainty}`}>{claim.certainty === 'inferred' ? 'Suggestion' : claim.certainty === 'unknown' ? 'Unknown' : 'Evidence-backed'}</span>{claim.evidence.map(id => <button key={id} className="evidence-link" onClick={() => setEvidence(sources.find(source => source.id === id) || null)}>↗ {sources.find(source => source.id === id)?.title || id}</button>)}</div></div>)}</div></article>)}</div></div><aside className={evidence ? 'evidence-panel open' : 'evidence-panel'}><div className="evidence-head"><div><p className="eyebrow">SUPPORTING EVIDENCE</p><h3>{evidence?.title || 'Select a citation'}</h3></div><button onClick={() => setEvidence(null)}>×</button></div>{evidence && <><span className="source-type">{evidence.type}</span><p className="evidence-detail">{evidence.detail}</p><pre className="evidence-content">{evidence.content || evidence.detail}</pre></>}<div className="panel-footer">Claims are only as strong as their sources. Mark a claim inaccurate or out of date after reviewing it.</div></aside></section>
    {showAdd && <div className="modal-backdrop"><form className="modal" onSubmit={addProject}><div><p className="eyebrow">ADD A PROJECT</p><h2>Start with your local evidence</h2><p>We read Git metadata and the note folders you select. Your repository is never changed.</p></div><label>Repository path<input required name="repositoryPath" placeholder="/Users/you/Projects/my-app" autoFocus /></label><label>Notes folder <small>(optional)</small><input name="notesPath" placeholder="/Users/you/Notes/my-app" /></label><label>Exclude paths <small>(comma-separated)</small><input name="excludedPaths" placeholder=".env, fixtures/large-data" /></label><div className="modal-actions"><button type="button" onClick={() => setShowAdd(false)}>Cancel</button><button className="primary" disabled={busy}>Add project</button></div></form></div>}
    {checkpointOpen && <div className="modal-backdrop"><div className="modal checkpoint"><div><p className="eyebrow">LEAVE CHECKPOINT</p><h2>Make your next return easier</h2><p>Edit the handoff before saving. It will become evidence for the next brief.</p></div><textarea defaultValue={'What changed:\n\nWhat remains:\n\nWhy this approach:\n\nNext step:'} /><div className="modal-actions"><button onClick={() => setCheckpointOpen(false)}>Cancel</button><button className="primary" onClick={saveCheckpoint}>Save checkpoint</button></div></div></div>}
  </main>
}
export default App
